---
# defaults file for elasticsearch

es_rpm_version: 7.10.2-1
es_yml:
  network_host: 0.0.0.0
  discovery_type: single-node
es_java_options:
  xms: 768m
  xmx: 768m
es_systemd_service:
  startup_timeout: 150
