---
# tasks file for janusgraph

- name: get cassandra nodes addresses
  set_fact:
    cassandra_nodes: "{{ groups['cassandra'] | join(', ') }}"

- name: get elasticsearch nodes addresses
  set_fact:
    elasticsearch_nodes: "{{ groups['elasticsearch'] | join(', ') }}"

- name: install java
  yum:
    name: java-{{ java_rpm_version }}
    state: present

- name: install unzip
  yum:
    name: unzip
    state: present

- name: add user
  user:
    name: "{{ janusgraph_user }}"

- name: unzip janusgraph release
  unarchive:
    src: https://github.com/JanusGraph/janusgraph/releases/download/v{{ janusgraph_version }}/janusgraph-{{ janusgraph_version }}.zip
    dest: /opt/
    owner: "{{ janusgraph_user }}"
    group: "{{ janusgraph_user }}"
    remote_src: yes
    creates: /opt/janusgraph-{{ janusgraph_version }}

- name: create symbolic link
  file:
    src: /opt/janusgraph-{{ janusgraph_version }}
    dest: /opt/janusgraph
    state: link

- name: put custom janusgraph-cql-es-server.properties
  template:
    src: templates/janusgraph-cql-es-server.properties
    dest: "/opt/janusgraph/conf/gremlin-server/"
    owner: "{{ janusgraph_user }}"
    group: "{{ janusgraph_user }}"
    mode: '0664'
  notify:
    - restart janusgraph

- name: put janusgraph.service
  template:
    src: templates/janusgraph.service
    dest: "/etc/systemd/system/"
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload systemd
    - restart janusgraph

- name: force handlers
  meta: flush_handlers

- name: enable janusgraph.service
  systemd:
    name: janusgraph
    enabled: yes
    state: started
